[programs.localnet]
slide = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/evanmdoyle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000

[test.validator]
url = "m"

# SPL Governance shared Program
[[test.validator.clone]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"

# SPL Governance shared Program Data Address
[[test.validator.clone]]
address = "BZYjZ2ZbtAawP9WPt5yXszcoMWTvNFFX4AMbnDojtSGL"

# Squads shared Program
[[test.validator.clone]]
# devnet
# address = "SQDSm7ifFqwmgxY5aL59BtHcBGHEgbg5thh4Y9ytdn3"
# devnet manual deploy
# address = "3BgFvAdsYQsX7MfudNcXcLFizyy2XSBL3uuZeUysR2p7"
# mainnet
address = "SQUADSxWKud1RVxuhJzNcqYqu7F3GLNiktGzjnNtriT"

# Squads shared Program Data Address
[[test.validator.clone]]
# devnet
# address = "4MCvGwea4ko8SGrKMxJoyFWdN8MD3vPNXLA2J1G6KyW6"
# devnet manual deploy
# address = "A3W5BA1NaQhmdmNaPfjfRXS1diwCbd8Xh7zTUyQ1omT5"
# mainnet
address = "2SzQW4XUwVjqeovfFpPJEZDU3rxCEekgbzq2AfL2mxq6"