[programs.localnet]
slide = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/evanmdoyle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000

[test.validator]
url = "https://api.devnet.solana.com"

# SPL Governance shared Program
[[test.validator.clone]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"

# Squads shared Program
[[test.validator.clone]]
address = "SQUADSxWKud1RVxuhJzNcqYqu7F3GLNiktGzjnNtriT"
